# Generated by Django 3.2.6 on 2022-01-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EBS2021', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='expirydate',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
